{
 "title": "Mina: Node Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "Instance",
    "query": "label_values(node_uname_info{job=~\"$job\",nodename=~\"$hostname\"},instance)"
   },
   {
    "name": "device",
    "label": "NIC",
    "query": "label_values(node_network_info{device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'},device)"
   },
   {
    "name": "maxmount",
    "label": "Max.Mount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
   },
   {
    "name": "show_hostname",
    "label": "Show Hostname",
    "query": "label_values(node_uname_info{job=~\"$job\",instance=~\"$node\"}, nodename)"
   }
  ]
 },
 "panels": [
  { "title": "Server Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes)",
     "legendFormat": "Used"
    },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Free" },
    { "expr": "node_memory_Buffers_bytes", "legendFormat": "Buffers" },
    { "expr": "node_memory_Cached_bytes", "legendFormat": "Cached" }
   ]
  },
  {
   "title": "Available Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes" }
   ]
  },
  { "title": "Mina Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Block Producer Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Coda_Block_producer_blocks_produced * 100 / Coda_Block_producer_slots_won"
    }
   ]
  },
  {
   "title": "Block Producer Stats",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "Coda_Block_producer_slots_won", "legendFormat": "Slot" },
    {
     "expr": "Coda_Block_producer_blocks_produced",
     "legendFormat": "Produce"
    },
    {
     "expr": "Coda_Block_producer_slots_won - Coda_Block_producer_blocks_produced",
     "legendFormat": "Gap (slot - produce)"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "Coda_Network_peers\n", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Blocks Produced",
   "type": "graph",
   "description": "blocks produced and submitted by the daemon",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "Coda_Block_producer_blocks_produced",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "delta(Messages Received) per 1 hour interval",
   "type": "graph",
   "description": "Average delay, in slots, after which produced blocks are received",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(Coda_Network_messages_received[1h])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Block Gossip Latency (Time)",
   "type": "graph",
   "description": "Average delay, in seconds, after which produced blocks are received",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "Coda_Block_latency_gossip_time", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Delta(slots won) per 3 hour intervals",
   "type": "graph",
   "description": "slots which the loaded block production keys have won (does not represent that a block was actually produced)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(Coda_Block_producer_slots_won[3h])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Mina Blockchain TPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Transactions" }
   ],
   "targets": [
    {
     "expr": "Coda_Transition_frontier_tps_30min",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "delta(VRF evaluations performed) per 3 hour intervals",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(Coda_Consensus_vrf_evaluations[3h])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Avg Network Slot Fill Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "Coda_Transition_frontier_slot_fill_rate * 100",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total[1m])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\"}))",
     "legendFormat": "{{ mode }}"
    }
   ]
  }
 ]
}