{
 "title": "Coda: Block Producer Performance Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "Instance",
    "query": "label_values(node_uname_info{job=~\"$job\",nodename=~\"$hostname\"},instance)"
   },
   {
    "name": "device",
    "label": "NIC",
    "query": "label_values(node_network_info{device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'},device)"
   },
   {
    "name": "maxmount",
    "label": "Max.Mount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
   },
   {
    "name": "show_hostname",
    "label": "Show Hostname",
    "query": "label_values(node_uname_info{job=~\"$job\",instance=~\"$node\"}, nodename)"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard (Dashboard panels are duplicated below)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Server Resource Overview (10 lines per page)",
   "type": "table-old",
   "description": "Partition utilization, disk read, disk write, download bandwidth, upload bandwidth, if there are multiple network cards or multiple partitions, it is the value of the network card or partition with the highest utilization rate collected.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"$job\"} - 0",
     "legendFormat": "Hostname"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{job=~\"$job\"})by(instance)",
     "legendFormat": "运行时间"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"$job\"} - 0",
     "legendFormat": "Memory"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=~\"$job\",mode='system'}) by (instance)",
     "legendFormat": "CPU Core #"
    },
    {
     "expr": "node_load5{job=~\"$job\"}",
     "legendFormat": "5 min load"
    },
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{job=~\"$job\",mode=\"idle\"}[5m])) by (instance)) * 100",
     "legendFormat": "CPU used %"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=~\"$job\"} / (node_memory_MemTotal_bytes{job=~\"$job\"})))* 100",
     "legendFormat": "Memory used %"
    },
    {
     "expr": "max((node_filesystem_size_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {job=~\"$job\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "Disk used %"
    },
    {
     "expr": "max(irate(node_disk_read_bytes_total{job=~\"$job\"}[5m])) by (instance)",
     "legendFormat": "Disk read"
    },
    {
     "expr": "max(irate(node_disk_written_bytes_total{job=~\"$job\"}[5m])) by (instance)",
     "legendFormat": "Disk write"
    },
    {
     "expr": "max(irate(node_network_receive_bytes_total{job=~\"$job\"}[5m])*8) by (instance)",
     "legendFormat": "Download"
    },
    {
     "expr": "max(irate(node_network_transmit_bytes_total{job=~\"$job\"}[5m])*8) by (instance)",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU Busy"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
     "legendFormat": "Used RAM Memory"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"})*100 /(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}))",
     "legendFormat": "Used Max Mount($maxmount)"
    },
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes{instance=~\"$node\"} + 1)/ (node_memory_SwapTotal_bytes{instance=~\"$node\"} + 1))) * 100",
     "legendFormat": "Used SWAP"
    }
   ]
  },
  {
   "title": "CPU iowait",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 5 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "Uptime % (24hr)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(delta(Coda_Runtime_process_uptime_ms_total[24h])/1000) * 100 / 86400"
    }
   ]
  },
  {
   "title": "Block Producer Rate (Last 30days)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Coda_Block_producer_blocks_produced * 100 / Coda_Block_producer_slots_won"
    }
   ]
  },
  {
   "title": "Block Producer Rate (Last 30days)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "Coda_Block_producer_slots_won", "legendFormat": "Slot" },
    {
     "expr": "Coda_Block_producer_blocks_produced",
     "legendFormat": "Produce"
    },
    {
     "expr": "Coda_Block_producer_slots_won - Coda_Block_producer_blocks_produced",
     "legendFormat": "Gap (slot - produce)"
    }
   ]
  },
  {
   "title": "Uptime percentage (Daily)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(delta(Coda_Runtime_process_uptime_ms_total[24h])/1000) * 100 / 86400",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"$node\", mode='system'})"
    }
   ]
  },
  {
   "title": "Total filefd",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_filefd_maximum{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 9 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Free inodes:$maxmount ",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_filesystem_files_free{instance=~\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext.?|xfs\"})"
    }
   ]
  },
  {
   "title": "Allocated Memory (1 per min)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "OS Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "OS Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "OS Avaliable"
    },
    {
     "expr": "Coda_Runtime_jemalloc_allocated_bytes",
     "legendFormat": "Coda Used"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
     "legendFormat": "Used%"
    }
   ]
  },
  {
   "title": "CPU (1 per min)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[5m])) by (instance) *100",
     "legendFormat": "System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[5m])) by (instance) *100",
     "legendFormat": "User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[5m])) by (instance) *100",
     "legendFormat": "Iowait"
    },
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) by (instance))*100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Blocks produced (1 per hour)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(Coda_Block_producer_blocks_produced[1h])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Blockchain Proving Time (1 per hour)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "delta(Coda_Cryptography_blockchain_proving_time_ms[1h])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Machine Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server Resource Overview (10 lines per page)",
     "type": "table-old",
     "description": "Partition utilization, disk read, disk write, download bandwidth, upload bandwidth, if there are multiple network cards or multiple partitions, it is the value of the network card or partition with the highest utilization rate collected.",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "node_uname_info{job=~\"$job\"} - 0",
       "legendFormat": "主机名"
      },
      {
       "expr": "sum(time() - node_boot_time_seconds{job=~\"$job\"})by(instance)",
       "legendFormat": "运行时间"
      },
      {
       "expr": "node_memory_MemTotal_bytes{job=~\"$job\"} - 0",
       "legendFormat": "总内存"
      },
      {
       "expr": "count(node_cpu_seconds_total{job=~\"$job\",mode='system'}) by (instance)",
       "legendFormat": "总核数"
      },
      {
       "expr": "node_load5{job=~\"$job\"}",
       "legendFormat": "5分钟负载"
      },
      {
       "expr": "(1 - avg(irate(node_cpu_seconds_total{job=~\"$job\",mode=\"idle\"}[5m])) by (instance)) * 100",
       "legendFormat": "CPU使用率"
      },
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{job=~\"$job\"} / (node_memory_MemTotal_bytes{job=~\"$job\"})))* 100",
       "legendFormat": "内存使用率"
      },
      {
       "expr": "max((node_filesystem_size_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {job=~\"$job\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"})))by(instance)",
       "legendFormat": "分区使用率"
      },
      {
       "expr": "max(irate(node_disk_read_bytes_total{job=~\"$job\"}[5m])) by (instance)",
       "legendFormat": "最大读取"
      },
      {
       "expr": "max(irate(node_disk_written_bytes_total{job=~\"$job\"}[5m])) by (instance)",
       "legendFormat": "最大写入"
      },
      {
       "expr": "max(irate(node_network_receive_bytes_total{job=~\"$job\"}[5m])*8) by (instance)",
       "legendFormat": "下载带宽"
      },
      {
       "expr": "max(irate(node_network_transmit_bytes_total{job=~\"$job\"}[5m])*8) by (instance)",
       "legendFormat": "上传带宽"
      }
     ]
    },
    {
     "title": "Total RAM",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 28 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 4, "x": 2, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) * 100)",
       "legendFormat": "CPU Busy"
      },
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
       "legendFormat": "Used RAM Memory"
      },
      {
       "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"})*100 /(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}))",
       "legendFormat": "Used Max Mount($maxmount)"
      },
      {
       "expr": "(1 - ((node_memory_SwapFree_bytes{instance=~\"$node\"} + 1)/ (node_memory_SwapTotal_bytes{instance=~\"$node\"} + 1))) * 100",
       "legendFormat": "Used SWAP"
      }
     ]
    },
    {
     "title": "CPU iowait",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 28 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[5m])) * 100"
      }
     ]
    },
    {
     "title": "【$show_hostname】：Disk Space Used Basic(EXT?/XFS)",
     "type": "table-old",
     "description": "In this kanban: the total disk, usage, available, and usage rate are consistent with the values of the Size, Used, Avail, and Use% columns of the df command, and the value of Use% will be rounded to one decimal place, which will be more accurate .\n\nNote: The Use% algorithm in df is: (size-free) * 100 / (avail + (size-free)), the result is divisible by this value, non-divisible by this value is +1, and the unit of the result is %.\nRefer to the df command source code:",
     "gridPos": { "h": 6, "w": 10, "x": 8, "y": 28 },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
       "legendFormat": "总量"
      },
      {
       "expr": "node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0"
      },
      {
       "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 30 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(node_cpu_seconds_total{instance=~\"$node\", mode='system'})"
      }
     ]
    },
    {
     "title": "Total filefd",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 30 },
     "format": "locale",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(node_filefd_maximum{instance=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 32 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(time() - node_boot_time_seconds{instance=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Free inodes:$maxmount ",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 32 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(node_filesystem_files_free{instance=~\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext.?|xfs\"})"
      }
     ]
    }
   ]
  },
  { "title": "Uptime Percentage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 26 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Uptime percentage (Daily)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 2, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(delta(Coda_Runtime_process_uptime_ms_total[24h])/1000) * 100 / 86400",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Uptime % (24hr)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(delta(Coda_Runtime_process_uptime_ms_total[24h])/1000) * 100 / 86400"
    }
   ]
  },
  {
   "title": "Uptime % (7days)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(delta(Coda_Runtime_process_uptime_ms_total[24h])/1000) * 100 / 86400"
    }
   ]
  },
  {
   "title": "Uptime % (30days)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 14, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(delta(Coda_Runtime_process_uptime_ms_total[24h])/1000) * 100 / 86400"
    }
   ]
  },
  { "title": "Allocated CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "CPU (1 per min)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[5m])) by (instance) *100",
     "legendFormat": "System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[5m])) by (instance) *100",
     "legendFormat": "User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[5m])) by (instance) *100",
     "legendFormat": "Iowait"
    },
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) by (instance))*100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU (3 hour avg)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[3h])) by (instance) *100",
     "legendFormat": "System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[3h])) by (instance) *100",
     "legendFormat": "User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[3h])) by (instance) *100",
     "legendFormat": "Iowait"
    },
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[3h])) by (instance))*100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU (daily avg)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[1d])) by (instance) *100",
     "legendFormat": "System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[1d])) by (instance) *100",
     "legendFormat": "User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[1d])) by (instance) *100",
     "legendFormat": "Iowait"
    },
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[1d])) by (instance))*100",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Allocated Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Allocated Memory (1 per min)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "OS Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "OS Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "OS Avaliable"
    },
    {
     "expr": "Coda_Runtime_jemalloc_allocated_bytes",
     "legendFormat": "Coda Used"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
     "legendFormat": "Used%"
    }
   ]
  },
  {
   "title": "Allocated Memory (3 hour avg)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(node_memory_MemTotal_bytes{instance=~\"$node\"}[3h])",
     "legendFormat": "OS Total"
    },
    {
     "expr": "avg_over_time(node_memory_MemTotal_bytes{instance=~\"$node\"}[3h]) - avg_over_time(node_memory_MemAvailable_bytes{instance=~\"$node\"}[3h])",
     "legendFormat": "OS Used"
    },
    {
     "expr": "avg_over_time(node_memory_MemAvailable_bytes{instance=~\"$node\"}[3h])",
     "legendFormat": "OS Avaliable"
    },
    {
     "expr": "avg_over_time(Coda_Runtime_jemalloc_allocated_bytes[3h])",
     "legendFormat": "Coda Used"
    },
    {
     "expr": "(1 - (avg_over_time(node_memory_MemAvailable_bytes{instance=~\"$node\"}[3h]) / (avg_over_time(node_memory_MemTotal_bytes{instance=~\"$node\"}[3h]))))* 100",
     "legendFormat": "Used%"
    }
   ]
  },
  {
   "title": "Allocated Memory (daily avg)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(node_memory_MemTotal_bytes{instance=~\"$node\"}[1d])",
     "legendFormat": "OS Total"
    },
    {
     "expr": "avg_over_time(node_memory_MemTotal_bytes{instance=~\"$node\"}[1d]) - avg_over_time(node_memory_MemAvailable_bytes{instance=~\"$node\"}[1d])",
     "legendFormat": "OS Used"
    },
    {
     "expr": "avg_over_time(node_memory_MemAvailable_bytes{instance=~\"$node\"}[1d])",
     "legendFormat": "OS Avaliable"
    },
    {
     "expr": "avg_over_time(Coda_Runtime_jemalloc_allocated_bytes[1d])",
     "legendFormat": "Coda Used"
    },
    {
     "expr": "(1 - (avg_over_time(node_memory_MemAvailable_bytes{instance=~\"$node\"}[1d]) / (avg_over_time(node_memory_MemTotal_bytes{instance=~\"$node\"}[1d]))))* 100",
     "legendFormat": "Used%"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Disk R/W Data",
   "type": "graph",
   "description": "Per second read / write bytes ",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}_Read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}_Written bytes"
    }
   ]
  },
  {
   "title": "Disk IOps Completed（IOPS）",
   "type": "graph",
   "description": "Read/write completions per second",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}_Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{device}}_Writes completed"
    }
   ]
  },
  {
   "title": "Open  File Descriptor(left)/Context switches(right)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 58 },
   "yaxes": [
    { "format": "short", "label": "used filefd" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$node\"}",
     "legendFormat": "used filefd"
    },
    {
     "expr": "irate(node_context_switches_total{instance=~\"$node\"}[5m])",
     "legendFormat": "switches"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Internet traffic per hour $device",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "bytes", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{instance=~\"$node\",device=~\"$device\"}[60m])",
     "legendFormat": "{{device}}_receive"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{instance=~\"$node\",device=~\"$device\"}[60m])",
     "legendFormat": "{{device}}_transmit"
    }
   ]
  },
  {
   "title": "Network bandwidth usage per second $device",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "bps", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$node',device=~\"$device\"}[5m])*8",
     "legendFormat": "{{device}}_receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$node',device=~\"$device\"}[5m])*8",
     "legendFormat": "{{device}}_transmit"
    }
   ]
  },
  {
   "title": "Network Sockstat",
   "type": "graph",
   "description": "Sockets_used - Sockets currently in use\n\nCurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT\n\nTCP_alloc - Allocated sockets\n\nTCP_tw - Sockets wating close\n\nUDP_inuse - Udp sockets currently in use\n\nRetransSegs - TCP retransmission packets\n\nOutSegs - Number of packets sent by TCP\n\nInSegs - Number of packets received by TCP",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~'$node'}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{instance=~'$node'}",
     "legendFormat": "Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=~'$node'}",
     "legendFormat": "UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~'$node'}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "irate(node_netstat_Tcp_InSegs{instance=~'$node'}[5m])",
     "legendFormat": "Tcp_InSegs"
    },
    {
     "expr": "irate(node_netstat_Tcp_OutSegs{instance=~'$node'}[5m])",
     "legendFormat": "Tcp_OutSegs"
    },
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{instance=~'$node'}[5m])",
     "legendFormat": "Tcp_RetransSegs"
    }
   ]
  },
  {
   "title": "% of slots | produce blocks for",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 }
  },
  {
   "title": "Block Producer Rate (Last 30days)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Coda_Block_producer_blocks_produced * 100 / Coda_Block_producer_slots_won"
    }
   ]
  },
  {
   "title": "Block Producer Rate (Last 30days)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "Coda_Block_producer_slots_won", "legendFormat": "Slot" },
    {
     "expr": "Coda_Block_producer_blocks_produced",
     "legendFormat": "Produce"
    },
    {
     "expr": "Coda_Block_producer_slots_won - Coda_Block_producer_blocks_produced",
     "legendFormat": "Gap (slot - produce)"
    }
   ]
  },
  { "title": "Allocated Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Disk Space Used% (1 per minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Disk Space Used% (3 hour interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 93 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Disk Space Used% (1 day interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 93 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Slots won", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Slots Won (1 per hour)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(Coda_Block_producer_slots_won[1h])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Slots Won (3 hour interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(Coda_Block_producer_slots_won[3h])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Slots Won (1 day interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(Coda_Block_producer_slots_won[1d])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Blocks produced", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "Blocks produced (1 per hour)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(Coda_Block_producer_blocks_produced[1h])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Blocks Produced (3 hour interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(Coda_Block_producer_blocks_produced[3h])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Block Produced (1 day interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "delta(Coda_Block_producer_blocks_produced[1d])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Time spent verifying VRFs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 } },
  {
   "title": "Time spent verifying VRFs (1 per hour)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(Coda_Consensus_vrf_evaluations[1h])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Time spent verifying VRFs (3 hour interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(Coda_Consensus_vrf_evaluations[3h])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Time spent verifying VRFs (1 day interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(Coda_Consensus_vrf_evaluations[1d])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Blockchain Proving Time (Seconds)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 }
  },
  {
   "title": "Blockchain Proving Time (1 per hour)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "delta(Coda_Cryptography_blockchain_proving_time_ms[1h])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Blockchain Proving Time (3 hour interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "delta(Coda_Cryptography_blockchain_proving_time_ms[3h])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Blockchain Proving Time (1 day interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "delta(Coda_Cryptography_blockchain_proving_time_ms[1d])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Block Gossip Latencies by Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137 } },
  {
   "title": "Block Gossip Latencies by Node (1 per hour)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(Coda_Block_latency_gossip_time[1h])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Block Gossip Latencies by Node (3 hour interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(Coda_Block_latency_gossip_time[3h])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Block Gossip Latencies by Node (1 day interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(Coda_Block_latency_gossip_time[1d])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Number of connected peers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 146 } },
  {
   "title": "Number of connected peers (1 hour avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(Coda_Network_peers[1h])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Number of connected peers (3 hour avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(Coda_Network_peers[3h])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Number of connected peers (1 day avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(Coda_Network_peers[1d])",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}